// 落羽杉配置和设置相关的


// 扩展工具目录字段
#define CONFIG_TOOL_EX_PATH "CONFIG_TOOL_EX_PATH"

// 截屏导出目录字段
#define CONFIG_SHOT_PIC_PATH "CONFIG_SHOT_PIC_PATH"

// 日志导出目录字段
#define CONFIG_SHOT_PIC_PATH "CONFIG_LOG_PULL_PATH"

// 常用目录使用字段
#define CONFIG_USE_PATH1 "CONFIG_USE_PATH1"
#define CONFIG_USE_PATH2 "CONFIG_USE_PATH2"
#define CONFIG_USE_PATH3 "CONFIG_USE_PATH3"
#define CONFIG_USE_PATH4 "CONFIG_USE_PATH4"
#define CONFIG_USE_PATH5 "CONFIG_USE_PATH5"
#define CONFIG_USE_PATH6 "CONFIG_USE_PATH6"
#define CONFIG_USE_PATH7 "CONFIG_USE_PATH7"
#define CONFIG_USE_PATH8 "CONFIG_USE_PATH8"
#define CONFIG_USE_PATH9 "CONFIG_USE_PATH9"
#define CONFIG_USE_PATH10 "CONFIG_USE_PATH10"
#define CONFIG_USE_PATH11 "CONFIG_USE_PATH11"
#define CONFIG_USE_PATH21 "CONFIG_USE_PATH12"